before_script:
  - echo $CI_PROJECT_NAME
  - echo $CI_PROJECT_NAMESPACE
  - echo $CI_REGISTRY
  - echo $CI_REGISTRY_IMAGE
  - echo $CI_REGISTRY_USER
  - echo $CI_DEFAULT_BRANCH

stages:
  - dockerbuild
  - build
  - test
  - deploy
    
dockerbuild:
  tags:
    - docker
  image: docker:latest
  stage: dockerbuild
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - ./scripts/dockerbuild.sh
  artifacts:
    paths:
      - docker-build.log
    expire_in: 1 week

build:
  stage: build
  tags:
    - docker
  artifacts:
    paths:
      - build/
  image: $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH
  script: 
    - mkdir build
    - cd build; cmake ..; make

test:
  stage: test
  dependencies:
  - build
  tags:
    - docker
  image: $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH
  script:
    - echo "Running the python tests"
    - python3 -m unittest tests
    # echo "Running the C++ tests"
    # ./build/scripts/kafka.sh start
    # run-parts --regex '.*Test' build/tests/cpp/
    # ./build/scripts/kafka.sh stop

deploy:
  only:
    - master 
  stage: deploy
  tags:
    - docker
  script:
    - echo SuCcEsS
