before_script:
  - echo $CI_PROJECT_NAME
  - echo $CI_PROJECT_NAMESPACE
  - echo $CI_REGISTRY
  - echo $CI_REGISTRY_IMAGE
  - echo $CI_REGISTRY_USER
  - echo $CI_DEFAULT_BRANCH

stages:
  - dockerbuild
  - build
  - test
  - upload
  - deploy

variables:
  PACKAGE_VERSION: "0.7"
  PACKAGE_REGISTRY_URL: "https://api.bintray.com/content/nashikun/tweetoscope/generic/${PACKAGE_VERSION}"

dockerbuild:
  stage: dockerbuild
  image: docker:latest
  only:
    - branches
  tags:
    - docker
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - ./scripts/dockerbuild.sh
  artifacts:
    paths:
      - docker-build.log
    expire_in: 1 week

build:
  stage: build
  image: $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH
  only:
    - branches
  tags:
    - docker
  artifacts:
    paths:
      - build/
  script: 
    - mkdir build
    - cd build; cmake ..; make

test:
  stage: test
  image: $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH
  only:
    - branches
  dependencies:
  - build
  tags:
    - docker
  script:
    - echo "Running the python tests"
    - python3 -m unittest tests
    # echo "Running the C++ tests"
    # ./build/scripts/kafka.sh start
    # run-parts --regex '.*Test' build/tests/cpp/
    # ./build/scripts/kafka.sh stop

deploy:
  stage: deploy
  only:
    - branches
    - master 
  dependencies:
    - build
  tags:
    - docker
  script:
    - echo SuCcEsS

upload:
  stage: upload
  image: curlimages/curl:latest
  rules:
  - if: $CI_COMMIT_TAG
  dependencies:
    - build
  script:
    - curl -T build/TweetCollector -unashikun:$BINARY_API_KEY ${PACKAGE_REGISTRY_URL}/TweetCollector-${CI_COMMIT_TAG}?publish=1
    - curl -T build/TweetGenerator -unashikun:$BINARY_API_KEY ${PACKAGE_REGISTRY_URL}/TweetGenerator-${CI_COMMIT_TAG}?publish=1