before_script:
  - echo $CI_PROJECT_NAME
  - echo $CI_PROJECT_NAMESPACE
  - echo $CI_REGISTRY
  - echo $CI_REGISTRY_IMAGE
  - echo $CI_REGISTRY_USER
  - echo $CI_DEFAULT_BRANCH

stages:
  - dockerbuild
  - build
  - test
  - deploy

variables:
  PACKAGE_VERSION: "0.7"
  PACKAGE_REGISTRY_URL: "https://api.bintray.com/content/nashikun/tweetoscope/generic/${PACKAGE_VERSION}"

dockerbuild:
  stage: dockerbuild
  image: docker:latest
  only:
    - branches
  tags:
    - docker
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab-student.centralesupelec.fr:4567
  script:
    - ./scripts/dockerbuild.sh
  artifacts:
    paths:
      - docker-build.log
    expire_in: 1 week

build:
  stage: build
  image: $CI_REGISTRY/$CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH
  only:
    - branches
  tags:
    - docker
  artifacts:
    paths:
      - build/
  script: 
    - mkdir build
    - cd build; cmake ..; make

test:
  stage: test
  image: $CI_REGISTRY/$CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH
  only:
    - branches
  dependencies:
  - build
  tags:
    - docker
  script:
    - echo "Running the python tests"
    - python3 -m unittest tests
    - echo "Running the C++ tests"
    - ./build/scripts/kafka.sh start
    - run-parts --regex '.*Test' build/tests/cpp/
    - ./build/scripts/kafka.sh stop

deploy:
  stage: deploy
  only:
    - master 
  dependencies:
    - build
  tags:
    - docker
  script:
    - echo SuCcEsS

upload:
  stage: deploy
  image: $CI_REGISTRY/$CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:$CI_DEFAULT_BRANCH
  tags:
    - docker
  rules:
  - if: $CI_COMMIT_TAG
  script:
    - mkdir build
    - cd build; cmake ..; make
    - curl -T TweetCollector -u nashikun:$BINARY_API_KEY ${PACKAGE_REGISTRY_URL}/TweetCollector-${CI_COMMIT_TAG}?publish=1
    - curl -T TweetGenerator -u nashikun:$BINARY_API_KEY ${PACKAGE_REGISTRY_URL}/TweetGenerator-${CI_COMMIT_TAG}?publish=1

pages:
  stage: deploy
  image: alpine:latest
  tags:
    - docker
  only:
    - master 
  dependencies:
    - build
  script:
    - mv build/doc/html public/
  artifacts:
    paths:
      - public
