apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  loki.yml: | 
    {"apiVersion": 1, "datasources": [{"access":"proxy", "editable": true, "name": "loki", "orgId": 1, "type": "loki", "url": "loki:3100", "version": 1}]}
  prometheus.yml: |
    {"apiVersion": 1,"datasources": [{"access":"proxy", "editable": true, "name": "prometheus", "orgId": 1, "type": "prometheus", "url": "http://prometheus-service.monitoring.svc:8080","version": 1}]}
