apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweet-estimator-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tweet-estimator-0
  template:
    metadata:
      name: tweet-estimator-0
      labels:
        app: tweet-estimator-0
    spec:
      containers:
      - name:  tweet-estimator-container 
        image: gitlab-student.centralesupelec.fr:4567/tweetoscope-mullticolore/tweetou/tweet-python
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /logs
          name: logs
        command: ["hawkes"]
        args : ["--config", "/config/hawkes_config.json","--partition", "0"]
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: logs
          hostPath:
            path: /logs
            type: DirectoryOrCreate

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweet-estimator-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tweet-estimator-1
  template:
    metadata:
      name: tweet-estimator-1
      labels:
        app: tweet-estimator-1
    spec:
      containers:
      - name:  tweet-estimator-container 
        image: gitlab-student.centralesupelec.fr:4567/tweetoscope-mullticolore/tweetou/tweet-python
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /logs
          name: logs
        command: ["hawkes"]
        args : ["--config", "/config/hawkes_config.json", "--partition", "1"]
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: logs
          hostPath:
            path: /logs
            type: DirectoryOrCreate
