apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweet-predictor-600
  replicas: 1
  selector:
    matchLabels:
      app: tweet-predictor-600
  template:
    metadata:
      name: tweet-predictor-600-pod
      labels:
        app: tweet-predictor-600
    spec:
      containers:
      - name: tweet-predictor-container
        image: gitlab-student.centralesupelec.fr:4567/tweetoscope-mullticolore/tweetou/tweet-python
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /logs
          name: logs
        command: ["predictor"]
        args : ["--config /config/deployment/predictor_config.json","--obs-window 600"]
        restartPolicy: OnFailure
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: logs
          hostPath:
            path: /logs
            type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweet-predictor-1200
  replicas: 1
  selector:
    matchLabels:
      app: tweet-predictor-1200
  template:
    metadata:
      name: tweet-predictor-1200-pod
      labels:
        app: tweet-predictor-1200
    spec:
      containers:
      - name: tweet-predictor-container
        image: gitlab-student.centralesupelec.fr:4567/tweetoscope-mullticolore/tweetou/tweet-python
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /logs
          name: logs
        command: ["predictor"]
        args : ["--config /config/deployment/predictor_config.json","--obs-window 1200"]
        restartPolicy: OnFailure
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: logs
          hostPath:
            path: /logs
            type: DirectoryOrCreate
