apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweet-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tweet-generator
  template:
    metadata:
      name: tweet-generator
      labels:
        app: tweet-generator
    spec:
      containers:
      - name: tweet-generator
        image: gitlab-student.centralesupelec.fr:4567/tweetoscope-mullticolore/tweetou/tweet-generator
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred
