apiVersion: v1
kind: Pod
metadata:
  name: kafka-pod
  labels:
    app: kafka-broker
spec:
  containers:
  - name: kafka-container
    image: wurstmeister/kafka
    imagePullPolicy: IfNotPresent
    env:
    - name: KAFKA_ADVERTISED_HOST_NAME
      value: kafka
    - name: KAFKA_CREATE_TOPICS
      value: "tweets:4:1,cascade_series:2:1,cascade_properties:2:1,logs:1:1"
    - name: HOST_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP 
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: "$(HOST_IP):30181"
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: KAFKA_ADVERTISED_LISTENERS        
      value: "PLAINTEXT://$(POD_IP):9092"

