apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  type: NodePort
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      targetPort: 2181
      port: 2181
      nodePort: 30181
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka-broker
  ports:
    - protocol: TCP
      targetPort: 9092
      port: 9092
