apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweet-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tweet-collector
  template:
    metadata:
      name: tweet-collector
      labels:
        app: tweet-collector
    spec:
      containers:
      - name: tweetcollector
        image: gitlab-student.centralesupelec.fr:4567/tweetoscope-mullticolore/tweetou/tweetcollector
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /logs
          name: logs
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: logs
          hostPath:
            path: /logs
            type: DirectoryOrCreate
