apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweetcollector-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      name: collector-pod
      labels:
        app: collector
    spec:
      containers:
      - name: tweetcollector-container
        image: gitlab-student.centralesupelec.fr:4567/tweetoscope-mullticolore/tweetou/tweetcollector
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred
