apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-config
data:
  vector.toml: |
    [sources.in]
      type="kafka"
      bootstrap_servers = "kafka-service:9092" # required
      group_id = "consumer-logs" # required
      topics = ["tweets"] # required

    [sinks.out]
      # General
      endpoint = "http://localhost:3100"
      inputs = ["in"] # required
      type = "loki" # required
      # Labels
      labels.key = "value" 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
data:
  config.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100

    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 5m
      chunk_retain_period: 30s

    schema_config:
      configs:
      - from: 2020-05-15
        store: boltdb
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 168h

    storage_config:
      boltdb:
        directory: /tmp/loki/index

      filesystem:
        directory: /tmp/loki/chunks

    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
data:
  config.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://localhost:3100/loki/api/v1/push

    scrape_configs:
    - job_name: logs
      pipeline_stages:
        - regex:
            expression: '\[(?P<Ts>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})\] {(?P<ThreadId>[0-9a-z]+)} <(?P<level>\w+)> \((?P<File>[a-zA-Z_.]+):(?P<Line>\d+)\) - (?P<Message>.*)'
        - timestamp:
            source: Ts
            format: 2006-01-02 15:04:05
        - output:
            source: Message
        - template:
            source: level
            template: '{{ ToUpper .Value }}'
        - labels:
            ThreadId:
            level:
            File:
            Message:
            Line:

      static_configs:
      - targets:
          - localhost
        labels:
          job: hawkes
          __path__: /logs/hawkes*.log
      - targets:
          - localhost
        labels:
          job: learner
          __path__: /logs/learner*.log
      - targets:
          - localhost
        labels:
          job: predictor
          __path__: /logs/predictor*.log
      - targets:
          - localhost
        labels:
          job: collector
          __path__: /logs/tweet_collector_*.log
