apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
data:
  config.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100

    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 5m
      chunk_retain_period: 30s

    schema_config:
      configs:
      - from: 2020-05-15
        store: boltdb
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 168h

    storage_config:
      boltdb:
        directory: /index-files/loki/index

      filesystem:
        directory: /index-files/loki/chunks

    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
data:
  config.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /index-files/positions.yaml

    clients:
      - url: http://localhost:3100/loki/api/v1/push

    scrape_configs:
    - job_name: logs
      pipeline_stages:
        - regex:
            expression: '\[(?P<Ts>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})\] {(?P<ThreadId>0x[0-9a-f]{16})} <(?P<level>\w+)> \((?P<File>[a-zA-Z_.]+):(?P<Line>\d+)\) - (?P<Message>.*0)'
        - timestamp:
            source: Ts
            format: 2006-01-02 15:04:05
        - output:
            source: Message
        - labels:
            ThreadId:
            level:
            File:
            Message:
            Line:

      static_configs:
      - targets:
          - localhost
        labels:
          job: collector
          __path__: /logs/tweet_collector_*.log
